name: Update gist with latest Bilibili videos
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Deno"
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 25b090391238b4eb9e31f08467fa973a
          UID: '24181982'
        run: deno run --allow-net --allow-env index.ts
